name: Code Style Check

on: [push, pull_request]

jobs:
  style:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x' # Укажите версию .NET SDK, которую вы используете

    - name: Restore dependencies
      run: dotnet restore

    - name: Check code style
      run: dotnet build --configuration Release /p:StyleCopTreatErrorsAsWarnings=false
